package org.krakaur.sendero.nativo;

import android.annotation.SuppressLint;
import android.app.*;
import android.content.*;
import android.content.res.ColorStateList;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

/** Android framework UI: no browser, WebView, HTML, or JavaScript runtime. */
public class MainActivity extends Activity {
    static final int CREAM=0xfffaf8ef,GREEN=0xff285b40,INK=0xff25382e,GOLD=0xffffe5a1,BLUE=0xff2d6380;
    static final int ANSWER_BASE=1100,NEXT=1200,SOLUTION=1201;
    private final ExecutorService io=Executors.newSingleThreadExecutor();
    private Store store; private JSONObject profile; private String route="home";
    private LinearLayout root,content;private ProgressBar activityIndicator;private boolean busy,pickerOpen,stopped;private long activeAt;private int accessEpoch;
    private static final int EXPORT=41,IMPORT=42,RESTORE=43;
    interface Work<T>{T run()throws Exception;} interface Result<T>{void accept(T value)throws Exception;}
    private <T> void work(Work<T> task,Result<T> done){
        if(busy)return;busy=true;int epoch=accessEpoch;if(root!=null)setEnabled(root,false);if(activityIndicator!=null)activityIndicator.setVisibility(View.VISIBLE);
        io.execute(()->{try{Bank.init(getApplicationContext());T value=task.run();runOnUiThread(()->{busy=false;if(isDestroyed())return;if(activityIndicator!=null)activityIndicator.setVisibility(View.GONE);if(epoch!=accessEpoch){profile=null;if(!stopped)loginScreen();return;}if(root!=null)setEnabled(root,true);try{done.accept(value);}catch(Exception e){error(e);}});}catch(Exception e){runOnUiThread(()->{busy=false;if(!isDestroyed()&&!stopped){if(activityIndicator!=null)activityIndicator.setVisibility(View.GONE);if(root!=null)setEnabled(root,true);if(epoch!=accessEpoch)loginScreen();error(e);}});}});
    }
    private void error(Exception e){new AlertDialog.Builder(this).setTitle("No se completó la acción").setMessage(e.getMessage()==null?"Inténtalo de nuevo. No borres los datos de la aplicación.":e.getMessage()).setPositiveButton("Entendido",null).show();}
    private void setEnabled(View v,boolean value){v.setEnabled(value);if(v instanceof android.view.ViewGroup){android.view.ViewGroup g=(android.view.ViewGroup)v;for(int i=0;i<g.getChildCount();i++)setEnabled(g.getChildAt(i),value);}}
    @Override public void onCreate(Bundle state){super.onCreate(state);store=new Store(this);getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);
        if(state!=null){route=state.getString("route","home");pickerOpen=state.getBoolean("picker",false);}
        if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,()->back());
        Object retained=getLastNonConfigurationInstance();if(retained instanceof String)work(()->store.profile((String)retained),p->{profile=p;render();});else loginScreen();
    }
    @Override public Object onRetainNonConfigurationInstance(){return profile==null?null:profile.optString("id");}
    @Override protected void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);state.putString("route",route);state.putBoolean("picker",pickerOpen);}
    @Override protected void onResume(){super.onResume();activeAt=SystemClock.elapsedRealtime();}
    @Override protected void onStart(){super.onStart();if(stopped){stopped=false;if(profile==null)loginScreen();}}
    @Override protected void onPause(){super.onPause();saveTime();activeAt=0;}
    @Override protected void onStop(){super.onStop();stopped=true;if(!isChangingConfigurations()&&!pickerOpen){accessEpoch++;profile=null;route="home";}}
    @Override protected void onDestroy(){super.onDestroy();io.execute(()->store.close());io.shutdown();}
    // Legacy Android requires this override; Android 13+ uses the callback registered above.
    @SuppressLint("GestureBackNavigation") @Override public void onBackPressed(){back();}
    private void back(){if(busy)return;if(profile!=null&&!route.equals("home")){saveTime();route="home";render();}else if(profile!=null)logout();else finish();}
    private void logout(){if(busy)return;saveTime();profile=null;route="home";loginScreen();}
    private void saveTime(){
        if(profile==null||busy||!route.equals("play")||profile.optJSONObject("current")==null)return;
        JSONObject snapshot=Engine.copy(profile);Engine.interruptTiming(Engine.currentQuestion(snapshot.optJSONObject("current")));addTime(snapshot);profile=snapshot;io.execute(()->{try{store.save(snapshot,null);}catch(Exception e){runOnUiThread(()->{if(!isDestroyed())error(e);});}});
    }
    private void addTime(JSONObject p){JSONObject s=p.optJSONObject("current");if(s==null)return;JSONObject q=Engine.currentQuestion(s);if(!q.optBoolean("done")&&activeAt>0&&route.equals("play")){if(SystemClock.elapsedRealtime()-activeAt>=60000)Engine.interruptTiming(q);try{if(s.has("race"))s.getJSONObject("race").put("elapsedMs",Math.min(86400000,s.getJSONObject("race").optLong("elapsedMs")+Math.min(60000,Math.max(0,SystemClock.elapsedRealtime()-activeAt))));q.put("activeMs",Math.min(86400000,q.optLong("activeMs")+Math.min(60000,Math.max(0,SystemClock.elapsedRealtime()-activeAt))));}catch(JSONException e){throw new IllegalStateException(e);}}activeAt=SystemClock.elapsedRealtime();}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    private GradientDrawable bg(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(18));return d;}
    private void shell(String subtitle){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CREAM);root.setPadding(dp(16),dp(8),dp(16),dp(8));setContentView(root);
        root.setOnApplyWindowInsetsListener((v,insets)->{if(Build.VERSION.SDK_INT>=30){Insets i=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());v.setPadding(dp(16)+i.left,dp(8)+i.top,dp(16)+i.right,dp(8)+i.bottom);}else{v.setPadding(dp(16)+insets.getSystemWindowInsetLeft(),dp(8)+insets.getSystemWindowInsetTop(),dp(16)+insets.getSystemWindowInsetRight(),dp(8)+insets.getSystemWindowInsetBottom());}return insets;});root.requestApplyInsets();
        TextView brand=text("SENDERO  /  Matemáticas",17,true);root.addView(brand);root.addView(text(subtitle,14,false));
        activityIndicator=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);activityIndicator.setIndeterminate(true);activityIndicator.setContentDescription("Guardando o abriendo datos");activityIndicator.setVisibility(View.GONE);root.addView(activityIndicator,new LinearLayout.LayoutParams(-1,dp(4)));
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(0,dp(16),0,dp(20));scroll.addView(content);
        if(profile!=null){LinearLayout nav=new LinearLayout(this);root.addView(nav);nav.addView(button("Inicio",()->navigate("home")),new LinearLayout.LayoutParams(0,-2,1));nav.addView(button("Avance",()->navigate("progress")),new LinearLayout.LayoutParams(0,-2,1));nav.addView(button("Salir",this::logout),new LinearLayout.LayoutParams(0,-2,1));for(int i=0;i<nav.getChildCount();i++)((Button)nav.getChildAt(i)).setTextSize(14);}
    }
    private TextView text(String s,int size,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextColor(INK);t.setTextSize(size);t.setPadding(dp(4),dp(6),dp(4),dp(6));if(bold)t.setTypeface(null,Typeface.BOLD);return t;}
    private Button button(String label,Runnable action){Button b=new Button(this);b.setText(label);b.setTextSize(16);b.setAllCaps(false);b.setTextColor(new ColorStateList(new int[][]{new int[]{-android.R.attr.state_enabled},new int[]{}},new int[]{0xff7e887d,GREEN}));b.setBackground(new android.graphics.drawable.InsetDrawable(new android.graphics.drawable.RippleDrawable(ColorStateList.valueOf(0xffb7d4bf),bg(0xffe5ecdf),null),dp(3),dp(4),dp(3),dp(4)));b.setElevation(0);b.setMinHeight(dp(52));b.setPadding(dp(8),dp(8),dp(8),dp(8));b.setOnClickListener(v->{if(!busy)action.run();});return b;}
    private void addButton(String label,Runnable action){content.addView(button(label,action),new LinearLayout.LayoutParams(-1,-2));}
    private void heading(String label){content.addView(text(label,28,true));}
    private void note(String label){content.addView(text(label,16,false));}
    private void navigate(String to){saveTime();route=to;render();}
    private void loginScreen(){if(isDestroyed())return;shell("Tus caminos se guardan en este teléfono");heading("Cada explorador, su camino");content.addView(new Landscape(this),new LinearLayout.LayoutParams(-1,dp(140)));note("Elige tu alias para entrar. Usa un apodo, sin nombre completo ni correo.");
        if(busy)return;work(()->store.profiles(),rows->{if(profile!=null)return;for(int i=0;i<rows.length();i++){JSONObject p=rows.getJSONObject(i);addButton(p.getString("alias"),()->loginDialog(p));}addButton("Crear perfil",this::createDialog);note("Hasta 8 perfiles. Si olvidas la contraseña, no hay recuperación por correo. Conserva una copia con una persona adulta de confianza.");});
    addButton("Recuperar copia protegida",()->{Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("application/json");pickerOpen=true;try{startActivityForResult(intent,RESTORE);}catch(ActivityNotFoundException e){pickerOpen=false;error(e);}});}
    private EditText input(String hint,boolean password){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(INK);e.setSingleLine(true);e.setMinHeight(dp(52));e.setInputType(password?InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD:InputType.TYPE_CLASS_TEXT);e.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(password?128:24)});return e;}
    private LinearLayout form(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(20),dp(8),dp(20),dp(8));return f;}
    private void loginDialog(JSONObject p){EditText pass=input("Contraseña",true);LinearLayout f=form();f.addView(pass);new AlertDialog.Builder(this).setTitle(p.optString("alias")).setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Entrar",(d,w)->{char[] password=pass.getText().toString().toCharArray();pass.setText("");work(()->store.login(p.optString("id"),password),value->{profile=value;if(profile.optJSONObject("current")!=null)Engine.interruptTiming(Engine.currentQuestion(profile.optJSONObject("current")));route="home";render();});}).show();}
    private void createDialog(){LinearLayout f=form();EditText alias=input("Alias (por ejemplo: Colibrí)",false),pass=input("Contraseña (mínimo 6 caracteres)",true),confirm=input("Repite la contraseña",true);f.addView(alias);f.addView(pass);f.addView(confirm);
        new AlertDialog.Builder(this).setTitle("Nuevo perfil local").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Crear",(d,w)->{if(!pass.getText().toString().equals(confirm.getText().toString())){error(new Exception("Las contraseñas no coinciden."));return;}char[] password=pass.getText().toString().toCharArray();String name=alias.getText().toString();pass.setText("");confirm.setText("");work(()->store.create(name,password),p->{profile=p;route="home";render();});}).show();
    }
    private void passwordDialog(){LinearLayout f=form();EditText old=input("Contraseña actual",true),next=input("Nueva contraseña",true),confirm=input("Repite la nueva contraseña",true);f.addView(old);f.addView(next);f.addView(confirm);new AlertDialog.Builder(this).setTitle("Cambiar contraseña").setView(f).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",(d,w)->{if(!next.getText().toString().equals(confirm.getText().toString())){error(new Exception("Las contraseñas no coinciden."));return;}String id=profile.optString("id");char[] a=old.getText().toString().toCharArray(),b=next.getText().toString().toCharArray();old.setText("");next.setText("");confirm.setText("");work(()->{store.changePassword(id,a,b);return true;},v->Toast.makeText(this,"Contraseña actualizada",Toast.LENGTH_LONG).show());}).show();}
    private void render(){if(profile==null){loginScreen();return;}shell(profile.optString("alias")+" · Sin conexión · v"+Engine.VERSION);switch(route){case "play":play();break;case "progress":progress();break;case "teacher":teacher();break;default:home();}}
    private void home(){heading("Un pequeño reto.\nUn nuevo descubrimiento.");content.addView(new Landscape(this),new LinearLayout.LayoutParams(-1,dp(160)));note("Elige práctica de cálculo o problemas para pensar. Cada camino tiene 8 retos y su propia dificultad. Las tablas hasta el 20 son una ampliación opcional.");
        note(profile.optString("playMode","race").equals("race")?"Modo: carrera con tres rivales virtuales. El nivel cambia entre carreras.":"Modo: práctica a mi ritmo, sin rivales.");
        addButton("Cambiar: carrera / a mi ritmo",()->mutate(p->{p.put("playMode",p.optString("playMode","race").equals("race")?"calm":"race");return null;},"home"));
        if(profile.optJSONObject("current")!=null)addButton("Continuar mi camino",()->navigate("play"));
        for(String trail:Engine.TRAILS)addButton(Engine.symbol(trail)+"  "+Engine.title(trail),()->{if(profile.optJSONObject("current")!=null){new AlertDialog.Builder(this).setTitle("Tienes un camino en marcha").setMessage("Termínalo antes de comenzar otro. Tu progreso está guardado.").setPositiveButton("Continuar",(d,w)->navigate("play")).setNegativeButton("Después",null).show();return;}mutate(p->{Engine.start(p,trail);if(!trail.equals("razonar")&&p.optString("playMode","race").equals("race")){JSONObject c=p.getJSONObject("current");c.put("race",Race.create(store.sessions(p.getString("id"),false),trail,c.getInt("level")));}return null;},"play");});
        addButton("Informes y acompañamiento",()->navigate("teacher"));addButton("Cambiar mi contraseña",this::passwordDialog);addButton("Copia protegida completa",this::backupDialog);note("La práctica orienta el acompañamiento; no sustituye una evaluación escolar ni mide por sí sola el aprendizaje.");
    }
    interface Mutation{JSONObject apply(JSONObject p)throws Exception;}
    private void mutate(Mutation action,String next){if(profile==null||busy)return;JSONObject p=Engine.copy(profile);addTime(p);work(()->{JSONObject completed=action.apply(p);store.save(p,completed);return p;},saved->{if(profile==null)return;profile=saved;route=next;render();});}
    private void play(){JSONObject s=profile.optJSONObject("current");if(s==null){route="progress";progress();return;}JSONObject q=Engine.currentQuestion(s);content.setPadding(0,0,0,dp(12));content.addView(text(Engine.title(s.optString("trail")),18,true));note("Reto "+(s.optInt("index")+1)+" de 8 · "+Engine.level(q.optInt("level")));if(s.has("race")){content.addView(new RaceView(this,s,()->s.optJSONObject("race").optLong("elapsedMs")+(activeAt>0&&!busy&&!stopped?Math.min(60000,Math.max(0,SystemClock.elapsedRealtime()-activeAt)):0),true),new LinearLayout.LayoutParams(-1,dp(160)));}else bar(s.optInt("index"),8,GREEN);String equation=q.optInt("a")+" "+Engine.symbol(s.optString("trail"))+" "+q.optInt("b");boolean reasoning=q.has("bankId");if(reasoning)note(q.optString("dimension")+(q.optString("pool").equals("transfer")?(q.optBoolean("novel")?" · Reto nuevo":" · Repaso de un reto"):""));TextView problem=text(reasoning?q.optString("prompt"):equation+" = ?",reasoning?23:32,true);problem.setGravity(Gravity.CENTER);if(reasoning||!q.optBoolean("solutionShown"))content.addView(problem);
        if(q.optBoolean("solutionShown")||q.optBoolean("done")){TextView solution=text("¡"+(reasoning?q.optString("solution"):equation+" = "+q.optInt("answer"))+"!",reasoning?26:32,true);solution.setId(SOLUTION);solution.setGravity(Gravity.CENTER);solution.setBackground(bg(GOLD));solution.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);content.addView(solution);if(reasoning)note(q.optString("explanation"));note(q.optBoolean("done")?"¡Lo encontraste! Puedes continuar cuando quieras.":"Toca la respuesta correcta para practicarla.");}
        JSONArray options=q.optJSONArray("options");for(int row=0;row<2;row++){LinearLayout line=new LinearLayout(this);content.addView(line);for(int col=0;col<2;col++){int index=row*2+col,value=options.optInt(index);Button b=button(Engine.option(q,value),()->mutate(p->{JSONObject current=p.getJSONObject("current");if(!current.getString("id").equals(s.optString("id"))||current.optInt("index")!=s.optInt("index"))return null;JSONObject item=Engine.currentQuestion(current);if(Engine.answer(item,value)&&item.optBoolean("done")&&!item.has("bankId"))return Engine.advance(p);return null;},"play"));b.setId(ANSWER_BASE+index);b.setTextSize(q.has("labels")?17:26);b.setMinHeight(dp(56));boolean used=false;for(int k=0;k<q.optJSONArray("attempts").length();k++)if(q.optJSONArray("attempts").optInt(k)==value)used=true;b.setEnabled(!q.optBoolean("done")&&!used);line.addView(b,new LinearLayout.LayoutParams(0,-2,1));}}
        if(q.optBoolean("hint"))note(hint(s.optString("trail"),q));
        if(!q.optBoolean("done")&&!q.optBoolean("hint"))addButton("Una pista",()->mutate(p->{Engine.currentQuestion(p.getJSONObject("current")).put("hint",true);return null;},"play"));
        if(q.optBoolean("done")){Button next=button(s.optInt("index")==7?"Ver mis avances":"Siguiente reto",()->mutate(Engine::advance,s.optInt("index")==7?"progress":"play"));next.setId(NEXT);content.addView(next);}activeAt=SystemClock.elapsedRealtime();
    }
    private String hint(String trail,JSONObject q){if(q.has("bankId"))return q.optString("hintText");int a=q.optInt("a"),b=q.optInt("b");if(trail.equals("suma"))return "Empieza en "+a+" y cuenta "+b+" pasos hacia adelante.";if(trail.equals("resta"))return "Empieza en "+a+" y retrocede "+b+" pasos.";return "Imagina "+a+" grupos. En cada grupo hay "+b+" semillas. Suma los grupos.";}
    private void bar(int numerator,int denominator,int color){ProgressBar b=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);b.setMax(Math.max(1,denominator));b.setProgress(numerator);b.setProgressTintList(ColorStateList.valueOf(color));b.setProgressBackgroundTintList(ColorStateList.valueOf(0xffdcded2));b.setContentDescription(numerator+" de "+denominator);content.addView(b,new LinearLayout.LayoutParams(-1,dp(14)));}
    private void dimension(String label,int value,int total,boolean support){int percent=total==0?0:Math.round(100f*value/total);note(label+": "+(total==0?"sin observaciones":value+" de "+total+" · "+percent+" %"));bar(value,total,support?BLUE:percent>=80?GREEN:percent>=50?0xffa66d0a:0xffa24c40);}
    private void metrics(JSONArray sessions,String trail,int level){int[] m=Engine.metrics(sessions,trail,level);dimension("Acierto en el primer intento",m[1],m[0],false);dimension("Resolución sin pista ni error",m[2],m[0],false);dimension("Uso de pistas",m[3],m[0],true);dimension("Respuesta correcta tras un error",m[5],m[4],true);note("Tiempo de interacción aproximado: "+(m[6]/1000)+" s. No equivale a asistencia ni tiempo total de estudio.");}
    private void reasoningMetrics(JSONArray sessions){
        Map<String,int[]> dims=new LinkedHashMap<>();int fresh=0,correct=0;
        for(int i=0;i<sessions.length();i++){JSONArray qs=sessions.optJSONObject(i).optJSONArray("questions");for(int j=0;j<qs.length();j++){JSONObject q=qs.optJSONObject(j);if(!q.has("bankId"))continue;int[] d=dims.get(q.optString("dimension"));if(d==null){d=new int[2];dims.put(q.optString("dimension"),d);}d[1]++;boolean independent=q.optJSONArray("attempts").length()==1&&q.optJSONArray("attempts").optInt(0)==q.optInt("answer")&&!q.optBoolean("hint");if(independent)d[0]++;if(q.optString("pool").equals("transfer")&&q.optBoolean("novel")){fresh++;if(independent)correct++;}}}
        if(dims.isEmpty())return;content.addView(text("Problemas para pensar",22,true));for(Map.Entry<String,int[]> d:dims.entrySet())dimension(d.getKey()+" · sin ayuda",d.getValue()[0],d.getValue()[1],false);dimension("Situaciones reservadas · sin ayuda",correct,fresh,false);note("Describe respuestas a estas tareas. No mide por sí solo razonamiento general ni explicación oral. En cada camino, conversa sobre cómo llegaste a la respuesta.");
    }
    private void progress(){heading(profile.optString("alias")+" · Mi progreso");String id=profile.optString("id");work(()->store.sessions(id,false),sessions->{if(profile==null||!route.equals("progress"))return;if(sessions.length()>0){JSONObject last=sessions.getJSONObject(sessions.length()-1);if(last.has("race")){heading("¡Llegaste a la meta!");content.addView(new RaceView(this,last,()->last.optJSONObject("race").optLong("elapsedMs"),false),new LinearLayout.LayoutParams(-1,dp(160)));note("Puntos de juego: 10 por reto completado + 5 por acierto inicial sin ayuda. No son una calificación.");}}note(sessions.length()+" caminos terminados. Los retos en curso aparecerán cuando termines el camino.");metrics(sessions,"",0);reasoningMetrics(sessions);for(String t:Engine.TRAILS){content.addView(text(Engine.title(t),22,true));for(int level=1;level<=4;level++){int[] m=Engine.metrics(sessions,t,level);dimension("Nivel "+level+" · primer intento",m[1],m[0],false);fluency(sessions,t,level);}}note("Fluidez: se suman los tiempos hasta la primera respuesta, incluidos los errores. Se excluyen pistas, interrupciones, correcciones y registros antiguos. No mide razonamiento general ni equivale a una carrera continua.");note("Verde: 80–100 %; ocre: 50–79 %; terracota: menos de 50 %. Azul: descripción de ayudas y correcciones. Los colores no son calificaciones ni diagnósticos. Comparar distintos niveles requiere cautela.");});}
    private void fluency(JSONArray sessions,String trail,int level){
        if(trail.equals("razonar"))return;double[] f=Engine.fluency(sessions,trail,level);
        if(f[0]+f[3]==0)return;
        note(f[0]>0?String.format(Locale.getDefault(),"Ritmo: %.1f aciertos/min de respuesta. Precisión inicial de los ejercicios medidos: %.0f%%. Basado en %.0f ejercicios; %.0f sin tiempo comparable.",60000*f[1]/f[2],100*f[1]/f[0],f[0],f[3]):"Sin tiempos comparables; registros antiguos, con pista o interrumpidos.");
    }
    private void fluencyAll(JSONArray sessions){
        note("Fluidez: 60 × aciertos iniciales / segundos hasta la primera respuesta, incluidos los errores iniciales. Excluye pistas, interrupciones, correcciones y registros antiguos. Es una tasa de respuesta en práctica, no una carrera continua ni una calificación. Compara por contenido y nivel.");
        for(String t:Engine.TRAILS)for(int l=1;l<=4;l++){double[] f=Engine.fluency(sessions,t,l);if(f[0]>0){note(Engine.title(t)+" · nivel "+l);fluency(sessions,t,l);}}
    }
    private void teacher(){heading("Compartir para acompañar");note("Los informes incluyen un identificador de perfil, respuestas y fechas. No incluyen alias ni contraseñas; son seudónimos, no anónimos. Entrégalos únicamente a la persona responsable.");addButton("Exportar informe JSON",()->export(false));addButton("Exportar tabla CSV",()->export(true));addButton("Recibir informe JSON",this::importReport);addButton("Ver informes recibidos",this::received);note("El envío es manual mediante el selector de archivos de Android. No hay servidor, envío automático ni recopilación para investigación. Importar conserva los informes separados y no modifica tu práctica.");note("Cada perfil ve sus propios informes recibidos. Esta edición no administra una escuela ni verifica la identidad de un docente.");}
    private void received(){String id=profile.optString("id");work(()->store.sessions(id,true),sessions->{if(profile==null)return;shell(profile.optString("alias")+" · Informes recibidos");heading("Registros para acompañar");Map<String,JSONArray> groups=new LinkedHashMap<>();for(int i=0;i<sessions.length();i++){JSONObject s=sessions.getJSONObject(i);String key=s.getString("profile");if(!groups.containsKey(key))groups.put(key,new JSONArray());groups.get(key).put(s);}if(groups.isEmpty())note("Todavía no hay informes recibidos.");for(Map.Entry<String,JSONArray> group:groups.entrySet()){note("Perfil: "+group.getKey());metrics(group.getValue(),"",0);fluencyAll(group.getValue());}addButton("Volver",()->navigate("teacher"));});}
    private void backupDialog(){
        EditText pass=new EditText(this);pass.setHint("Contraseña de respaldo: mínimo 10 caracteres");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);
        new AlertDialog.Builder(this).setTitle("Copia protegida completa").setMessage("Guarda esta contraseña por separado. La copia conserva perfil, adaptación, partida e informes. Es un formato para Android, diferente del respaldo web.").setView(pass).setNegativeButton("Cancelar",null).setPositiveButton("Preparar",(d,w)->{
            String id=profile.optString("id");char[] password=pass.getText().toString().toCharArray();pass.setText("");work(()->{JSONObject encrypted=BackupCrypto.encrypt(store.snapshot(id),password);try(FileOutputStream out=new FileOutputStream(pending())){out.write(encrypted.toString().getBytes(StandardCharsets.UTF_8));}return true;},v->{Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT);intent.setType("application/json");intent.addCategory(Intent.CATEGORY_OPENABLE);intent.putExtra(Intent.EXTRA_TITLE,"Sendero-respaldo-Android.json");pickerOpen=true;startActivityForResult(intent,EXPORT);});
        }).show();
    }
    private void restoreDialog(JSONObject encrypted){
        LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);EditText pass=new EditText(this),next=new EditText(this);pass.setHint("Contraseña del respaldo");next.setHint("Nueva contraseña del perfil");for(EditText e:new EditText[]{pass,next}){e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);form.addView(e);}
        new AlertDialog.Builder(this).setTitle("Recuperar perfil Android").setMessage("Se recuperará una copia completa con nueva contraseña. No se reemplazará un perfil existente.").setView(form).setNegativeButton("Cancelar",null).setPositiveButton("Recuperar",(d,w)->{char[] backupPass=pass.getText().toString().toCharArray(),newPass=next.getText().toString().toCharArray();pass.setText("");next.setText("");work(()->{try{return store.restore(BackupCrypto.decrypt(encrypted,backupPass),newPass);}finally{Arrays.fill(backupPass,'\0');Arrays.fill(newPass,'\0');}},p->{profile=null;loginScreen();Toast.makeText(this,"Perfil recuperado. Entra con la nueva contraseña.",Toast.LENGTH_LONG).show();});}).show();
    }
    private File pending(){return new File(getCacheDir(),"pending-export.txt");}
    private void export(boolean csv){String id=profile.optString("id");work(()->{JSONArray sessions=store.sessions(id,false);String data=csv?Engine.csv(sessions):Engine.report(id,sessions).toString(2);try(FileOutputStream out=new FileOutputStream(pending())){out.write(data.getBytes(StandardCharsets.UTF_8));}return true;},v->{Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType(csv?"text/csv":"application/json");intent.putExtra(Intent.EXTRA_TITLE,"Sendero-"+id.substring(0,8)+(csv?".csv":".json"));pickerOpen=true;try{startActivityForResult(intent,EXPORT);}catch(ActivityNotFoundException e){pickerOpen=false;error(new Exception("Este dispositivo no tiene selector de archivos habilitado."));}});}
    private void importReport(){Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("*/*");pickerOpen=true;try{startActivityForResult(intent,IMPORT);}catch(ActivityNotFoundException e){pickerOpen=false;error(new Exception("Este dispositivo no tiene selector de archivos habilitado."));}}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);pickerOpen=false;if(result!=RESULT_OK||data==null||data.getData()==null){pending().delete();return;}Uri uri=data.getData();if(request==RESTORE){work(()->{try(InputStream in=getContentResolver().openInputStream(uri);ByteArrayOutputStream out=new ByteArrayOutputStream()){if(in==null)throw new IOException("Archivo no disponible.");byte[] buffer=new byte[8192];int n,total=0;while((n=in.read(buffer))!=-1){total+=n;if(total>30*1024*1024)throw new IOException("Copia demasiado grande.");out.write(buffer,0,n);}return new JSONObject(new String(out.toByteArray(),StandardCharsets.UTF_8));}},this::restoreDialog);return;}if(request==EXPORT){work(()->{try(InputStream in=new FileInputStream(pending());OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new IOException("No se pudo abrir el archivo.");byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);}pending().delete();return true;},v->Toast.makeText(this,"Informe guardado",Toast.LENGTH_LONG).show());}else if(request==IMPORT){if(profile==null){error(new Exception("Vuelve a entrar en tu perfil y selecciona el informe."));return;}String id=profile.optString("id");work(()->{try(InputStream in=getContentResolver().openInputStream(uri);ByteArrayOutputStream out=new ByteArrayOutputStream()){if(in==null)throw new IOException("No se pudo abrir el archivo.");byte[] buffer=new byte[8192];int n,total=0;while((n=in.read(buffer))!=-1){total+=n;if(total>10*1024*1024)throw new IOException("El informe supera el límite de 10 MB.");out.write(buffer,0,n);}return store.receive(id,new JSONObject(new String(out.toByteArray(),StandardCharsets.UTF_8)));}},count->new AlertDialog.Builder(this).setTitle("Informe recibido").setMessage(count+" sesiones nuevas. Los duplicados idénticos no se cuentan dos veces.").setPositiveButton("Entendido",null).show());}}
    private static class Landscape extends View {
        final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);final Path p=new Path();Landscape(Context c){super(c);setImportantForAccessibility(IMPORTANT_FOR_ACCESSIBILITY_NO);}
        void color(int value){paint.setColor(value);}
        @Override protected void onDraw(Canvas canvas){super.onDraw(canvas);float w=getWidth(),h=getHeight();color(0xffe7eddd);canvas.drawRoundRect(0,0,w,h,28,28,paint);color(0xfff4c65b);canvas.drawCircle(w*.78f,h*.25f,h*.13f,paint);p.reset();p.moveTo(0,h);p.lineTo(w*.27f,h*.15f);p.lineTo(w*.6f,h);p.close();color(0xff9bbba1);canvas.drawPath(p,paint);p.reset();p.moveTo(w*.35f,h);p.lineTo(w*.69f,h*.28f);p.lineTo(w,h);p.close();color(0xff5e896e);canvas.drawPath(p,paint);color(0xffffe5a1);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(h*.1f);p.reset();p.moveTo(w*.45f,h);p.cubicTo(w*.7f,h*.7f,w*.42f,h*.65f,w*.58f,h*.48f);canvas.drawPath(p,paint);paint.setStyle(Paint.Style.FILL);color(0xffbf6c3b);canvas.drawCircle(w*.21f,h*.7f,h*.11f,paint);p.reset();p.moveTo(w*.21f-h*.09f,h*.64f);p.lineTo(w*.21f-h*.09f,h*.49f);p.lineTo(w*.21f,h*.61f);p.lineTo(w*.21f+h*.09f,h*.49f);p.lineTo(w*.21f+h*.09f,h*.64f);p.close();canvas.drawPath(p,paint);color(CREAM);canvas.drawCircle(w*.21f,h*.75f,h*.055f,paint);color(INK);canvas.drawCircle(w*.21f-h*.035f,h*.67f,h*.012f,paint);canvas.drawCircle(w*.21f+h*.035f,h*.67f,h*.012f,paint);}
    }
}

